// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHSLP5-XA8YmmKSqOGy7rk7mH2hazheoU',
    appId: '1:63455719843:web:5476621db58612913faa16',
    messagingSenderId: '63455719843',
    projectId: 'chatapp-6c1ca',
    authDomain: 'chatapp-6c1ca.firebaseapp.com',
    storageBucket: 'chatapp-6c1ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF3bT2Cz8DkUYqX6hmnuzOyxdSxEMJtIs',
    appId: '1:63455719843:android:288749412a054e283faa16',
    messagingSenderId: '63455719843',
    projectId: 'chatapp-6c1ca',
    storageBucket: 'chatapp-6c1ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNcI1t-wBFGqo7GfouWcCMMAnwfITvLk',
    appId: '1:63455719843:ios:ddcb5455f189fd833faa16',
    messagingSenderId: '63455719843',
    projectId: 'chatapp-6c1ca',
    storageBucket: 'chatapp-6c1ca.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLNcI1t-wBFGqo7GfouWcCMMAnwfITvLk',
    appId: '1:63455719843:ios:ddcb5455f189fd833faa16',
    messagingSenderId: '63455719843',
    projectId: 'chatapp-6c1ca',
    storageBucket: 'chatapp-6c1ca.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHSLP5-XA8YmmKSqOGy7rk7mH2hazheoU',
    appId: '1:63455719843:web:ee1733901c1e697a3faa16',
    messagingSenderId: '63455719843',
    projectId: 'chatapp-6c1ca',
    authDomain: 'chatapp-6c1ca.firebaseapp.com',
    storageBucket: 'chatapp-6c1ca.firebasestorage.app',
  );
}
